spring:
  application:
    name: mortgage_eligibility_checker
  profiles:
    active: prod
  lifecycle:
    timeout-per-shutdown-phase: 20s
springdoc:
  api-docs:
    path: /api-docs
logging:
  level:
    root: INFO
# Container config
server:
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
# Custom app props
mortgage:
  max-loan-amount: 100000000
  max-monthly-interest-rate: 1.0
  max-maturity-months: 1200
